### ISSUE TITLE
[RHI-530] solady remappings

### ISSUE THREAD

**Issue by zeroknots** [rhinestonewtf/modulekit#11]
solady imports currently dont follow forge remapping standard.

devs using modulekit have to append `/src/ `to the solady remapping

<sub>[RHI-530](https://linear.app/rhinestone/issue/RHI-530/solady-remappings)</sub>

**Comment by kopy-kat** [comment]
This should have been fixed in https://github.com/rhinestonewtf/modulekit/commit/37b2e6f41ce86a9dce3afbfca51610de52825dde
