### ISSUE TITLE
[Safe7579]: [Add Solidity Prettier Linting]

### ISSUE THREAD

**Issue by kanthgithub** [rhinestonewtf/modulekit#92]
## Change Proposal
Add prettier linting for solidity contracts
- printWidth: 120
- tabWidth: 2
- bracketSpacing: true
-  useTabs": false
-  singleQuote": false

## Purpose:
- Fix Linting build failures
- Standard formatting across all solidity contracts

**Comment by zeroknots** [comment]
nope
